### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by Queenenrd17** [slonopot/Beenius#1]
Hiya, When I try to add your plugin I get an error saying Exception has been Thrown By the Target of an invocation

**Comment by slonopot** [comment]
Try updating MusicBee to the [latest](https://getmusicbee.com/forum/index.php?topic=36464.msg204388#msg204388) version and try again. If an exception occurs, the plugin is being disabled in Settings, make sure to enable it again and check if it works.

**Comment by slonopot** [comment]
Also make sure you unpack the dlls straight into Plugins folder and not in the subfolders as it may cause an issue.
