### ISSUE TITLE
How to install for musicbee installed via Microsoft Store and not via the official installer?

### ISSUE THREAD

**Issue by ThedankDank** [slonopot/Beenius#5]
I have tried to see the instructions to follow but i am not able to find the directory of the musicbee plugins folder. Pls help!

**Comment by slonopot** [comment]
Take a look at `C:/Users/<>/AppData/Local/Packages`, there should be an isolated container for the msstore app and maybe you'll be allowed to put the plugin there. Otherwise just stick to the normal version, it's way easier to handle imo.
