### ISSUE TITLE
Lyrics in non-Latin alphabets

### ISSUE THREAD

**Issue by bhankerson** [slonopot/Beenius#7]
Hi, another question I have that may be dumb: none of the lyircs finders I have activated (Beenius, Museexmatch, and all of the ones from LyricsReloaded and Lyrics Plugin) can find lyrics for songs I have in cyrillic script. I'm not sure which one it was, but the base MusicBee fetchers used to be able to find them. For example, Okean Elzy (Океан Ельзи) has all their lyrics on Genius.com, but the website with the lyrics has a URL in latin, with the song titles translated (not transliterated). Typing the URL in cyrillic with the song's native Ukrainian title doesn't get me anywhere (sounds obvious, but that does work for some other types of websites).
Do you know of any databases of cyrillic-language lyrics (I also have songs in Russian, Kazakh, and Mongolian), or is there a way to get Genius to recognize the original language? Thanks!

**Comment by slonopot** [comment]
The lookup process is primitive, we don't have a way to sync the naming and we expect it to just work. For example, If you have a track that's tagged as **Океан Ельзи -- Обійми**, Genius knows it as **Океан Ельзи (Okean Elzy) -- Обійми (Hug)**. The plugin will match **Океан Ельзи** to **Океан Ельзи (Okean Elzy)** and will fail doing so. As both my plugins by default allow no more than 5 (or 3) mismatched characters, you can change the distance in config to 100, manually launch missing lyrics lookup by album and just pray it's gonna work.

**Comment by bhankerson** [comment]
What do you mean by "the plugin will match Океан Ельзи to Океан Ельзи (Okean Elzy) and will fail doing so"?
Do I have it right, that other than increasing the allowedDistance and hoping, the only way to pull Genius would be to translate all the song titles?

**Comment by slonopot** [comment]
This literally means that there's no **Океан Ельзи -- Обійми** on Genius, there's **Океан Ельзи (Okean Elzy) -- Обійми (Hug)** on Genius and your artist and title will be matched agains Genius' artist and title and with strict configuration will fail for the obvious reason. With your library and how it's named and the way Genius handles foreign titles it seems reasonable to just sync it once with fingers crossed and never come back. I've mentioned in the previous issue that audio tagging is a mess, it's an example of a mess
