### ISSUE TITLE
cannot enable plugin

### ISSUE THREAD

**Issue by conniebecool** [slonopot/Beenius#8]
mb_beenius.dll is showing up in the plugins folder but when i click enable i get error "unable to initialise plugin: mb_Beenius.dll Exception has been thrown by the target of an invocation."

**Comment by slonopot** [comment]
Hey,

Let's make sure that you have all the necessary files in their places. Open Explorer and put `%APPDATA%\MusicBee\Plugins` in the location (to the left from the search bar, where your current location is displayed). Alternatively you can navigate to `AppData\Roaming\MusicBee\Plugins` manually. In this folder you should have at least mb_Beenius.dll, NLog.dll and Topten.JsonKit.dll.

If these are all present, try navigating to https://api.genius.com in your browser, you should see `Action forbidden for current scope` and this will confirm you can access the API at all.

You can also check if your plugin version is [the latest](https://github.com/slonopot/Beenius/releases/tag/v1.3.7), you can just copy all the files to the Plugins folder and overwrite (make sure MusicBee is closed though).
